name: Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'restart.sh'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          CR_PAT: ${{ secrets.CP_PAT }}
        run: echo $CR_PAT | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build the Docker image
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/cronrestarter:latest
      - name: Docker push
        run: docker push ghcr.io/${{ github.repository_owner }}/cronrestarter:latest
